"""
Модуль ответов сервера на запросы.
"""
TOKEN_EXPIRED = 'TOKEN_EXPIRED'
TOKEN_INVALID = 'TOKEN_INVALID'

AUTHORIZATION_REQUIRED = 'AUTHORIZATION_REQUIRED'
INCORRECT_USERNAME_OR_PASSWORD_ENTERED = 'INCORRECT_USERNAME_OR_PASSWORD_ENTERED'

USER_IS_NOT_FOUND = 'USER_IS_NOT_FOUND'
PASSWORD_FAIL_CONDITIONS = 'PASSWORD_FAIL_CONDITIONS'
PASSWORD_DO_NOT_MATCH = 'PASSWORD_DO_NOT_MATCH'

YOU_CANNOT_DELETE_YOURSELF = 'YOU_CANNOT_DELETE_YOURSELF'

NOT_ENOUGH_PERMISSIONS = 'NOT_ENOUGH_PERMISSIONS'
